config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"

 get "/login", to: "sessions#new"
 post "/login", to: "sessions#create"
 delete "/logout", to: "sessions#destroy"


    resources :users, only:[:new, :create, :show] do
      resources :ideas
    end
    namespace :admin do
      resources :images
    resources :categories, only: [:index, :new, :destroy, :edit, :update, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  validates :title, presence: true
  has_many :ideas

end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :name, :content, presence: true
    belongs_to :user
    belongs_to :category, optional: true

    has_many :idea_images, dependent: :nullify
    has_many :images, through: :idea_images
end

app/models/idea_image.rb
class IdeaImage < ApplicationRecord
  belongs_to :idea
  belongs_to :image
end 

app/models/image.rb
class Image < ApplicationRecord

has_many :idea_images, dependent: :nullify
has_many :ideas, through: :idea_images


end

app/models/user.rb
class User < ApplicationRecord

  validates_presence_of :name, :email, :password

  has_secure_password
  has_many :ideas

  enum role: ["default", "admin"]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin


    private

    def require_admin
      render file: "/public/404" unless current_admin?
    end

  end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController


  def index
    @categories = Category.all
    @image = Image.all
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to admin_categories_path
  end

  def edit
   @category = Category.find(params[:id])

  end

  def new
    @category = Category.new
    @image = Image.new
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    if @category.save
     redirect_to admin_categories_path
   else
     render :edit
   end
 end

  private

  def category_params
    params.require(:category).permit(:title)
  end

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController


  def index
    @images = Image.all
  end

  def edit
    @image = Image.find(params[:id])
  end

  def destroy
    image = Image.find(params[:id])
    image.destroy
    redirect_to admin_images_path
  end

  def show
    @image = Image.find(params[:id])
  end


  def new
   @image = Image.new
 end

 def create
   @image = Image.create(image_params)
   redirect_to admin_images_path

 end

  private

  def image_params
    params.require(:image).permit(:name, :url)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  def current_admin?
    current_user && current_user.admin?
  end



end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index

  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @idea = @user.ideas.new
    @image = Image.all
    redirect_to root_path unless @user == current_user
  end

  def create
    @user = User.find(params[:user_id])
    @idea = @user.ideas.create(idea_params)
    @idea.image_ids = params[:image_url]
    redirect_to user_ideas_path(@user)
  end

  def index
    @user = User.find(params[:user_id])
    @ideas = @user.ideas
    @image = Image.all
    redirect_to root_path unless @user == current_user
  end

  def edit
    @user = User.find(params[:user_id])
    @idea = Idea.find(params[:id])
    @categories = Category.all
    @images = Image.all
  end

  def show
   @user = User.find(params[:user_id])
   @idea = Idea.find(params[:id])

   redirect_to root_path unless @user == current_user
  end

  def destroy
    Idea.destroy(params[:id])
    redirect_to user_ideas_path(params[:user_id])
  end

  def update
    @idea = Idea.find(params[:id])
    @category = Category.all
    @user = User.find(params[:user_id])
    @idea.image_ids = params[:image_url]
    @idea.update(idea_params)
    redirect_to user_idea_path(@user, @idea)
  end

  private

  def idea_params
    params.require(:idea).permit(:content, :name, :image, :category_id, {:image_ids => []})
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def create
    @user = User.find_by(name: params[:name])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def new

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "successfully logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end


  def show
    @user = User.find(params[:id])
    redirect_to root_path unless @user == current_user
  end


  private

  def user_params
    params.require(:user).permit(:name, :password, :email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  module ApplicationHelper
    def bootstrap_class_for flash_type
      { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
    end

    def flash_messages(opts = {})
      flash.each do |msg_type, message|
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
          concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
            concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
            concat content_tag(:span, 'Close', class: 'sr-only')
          end)
          concat message
        end)
      end
      nil
    end
  end
end

app/views/admin/categories/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <header>
    <img class=""src="https://i.imgur.com/Q8V6tqc.jpg" alt="banner" height="300px" width="100%">
  </header>
  <body>
    <div class="login-5">
      <div class="wrapper">
        <%= form_for [:admin, @category] do |f| %>
        <%= f.label :title%>
        <%= f.text_field :title, placeholder: "New category name.*" %><br><br>
        <%= f.submit class: "sub-btn" %>
        <% end %>
      </div>
  </body>
</html>

app/views/admin/categories/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css">
  </head>
  <header>
    <img class="animated flipInY"src="https://i.imgur.com/CERSYlK.jpg" alt="banner" height="300px" width="100%">
  </header>
  <body>
    <div class="btn btn-info">
      <%= button_to "Home", user_path(current_user), method: "get" %><br/>
    </div>
    <div id="left"></div>
    <div id="right"></div>
    <div id="top"></div>
    <div id="bottom"></div>


        <% @categories.each do |category| %>
        <div class="flex-container">
          <div>
        <h2><%= category.title %></h2>
        <br>
        <span class="button-wrap">
          <div class="button button-raised button-primary button-pill">
            <%= link_to "Delete",   admin_category_path(category), method: "delete" %>
          </div>
        </span>
        <span class="button-wrap">
          <div class="button button-raised button-primary button-pill">
             <%= link_to "Edit", edit_admin_category_path(category) %>
          </div>
        </span>
      </div>

    </div>
        <% end %>
    <div class="btn btn-info">
  </div>
</body>
</html>

app/views/admin/categories/new.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <header>
    <img class=""src="https://i.imgur.com/PHJtGpv.jpg" alt="banner" height="300px" width="100%">
  </header>
  <body>
    <div id="left"></div>
    <div id="right"></div>
    <div id="top"></div>
    <div id="bottom"></div>
    <div class="login-5">
      <div class="wrapper">
        <%= form_for [:admin, @category] do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title, placeholder: "new category*" %><br>
        <%= f.submit class: "sub-btn" %>
      </div>
      <% end %>
      <br>
      <div class="wrapper">
        <%= form_for [:admin, @image] do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "name for image*" %><br>
        <%= f.label :url %>
        <%= f.text_field :url, placeholder: "Image url*" %><br>
        <%= f.submit class: "sub-btn" %>
      </div>
      <% end %>
    </body>
</html>

app/views/admin/images/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css">
  </head>
  <header>
    <img class="animated flipInY"src="https://i.imgur.com/O4V862J.jpg" alt="banner" height="300px" width="100%">
  </header>
  <body>
    <div class="btn btn-info">
      <%= button_to "Home", user_path(current_user), method: "get" %><br/>
    </div>
    <div id="left"></div>
    <div id="right"></div>
    <div id="top"></div>
    <div id="bottom"></div>

        <% Image.all.each do |image| %>

        <%= image_tag(image.url, :class=> "img-circular")%>
        <%= check_box_tag("image_url[]",image.id) %>
        <span class="button-wrap">
          <div class="button button-raised button-primary button-pill">
            <%= link_to "Delete", admin_image_path(image), method: "delete" %>
          </div>
        </span>
        <% end %>
  </div>
</body>
</html>

app/views/admin/images/new.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <header>
    <img class=""src="https://i.imgur.com/TfJH34P.jpg" alt="banner" height="300px" width="100%">
  </header>
  <body>
    <div id="left"></div>
    <div id="right"></div>
    <div id="top"></div>
    <div id="bottom"></div>
    <div class="login-5">
      <br>
      <div class="wrapper">
        <%= form_for [:admin, @image] do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "name for image*" %><br>
        <%= f.label :url %>
        <%= f.text_field :url, placeholder: "Image url*" %><br>
        <%= f.submit class: "sub-btn" %>
      </div>
      <% end %>
    </body>
</html>

app/views/dashboard/index.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/buttons.css">
    <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css">
  </head>
  <header>
    <img class="animated bounceInDown"src="https://i.imgur.com/ydRkyuu.jpg" alt="banner" height="300px" width="100%">
  </header>
  <body>
    <div id="left"></div>
    <div id="right"></div>
    <div id="top"></div>
    <div id="bottom"></div>
    <div class="login animated slideInUp">
      <span class="button-wrap">
        <div class="button button-raised button-primary button-pill">
          <%= link_to "Sign Up", new_user_path %>
        </div>
      </span>
      <br>
      <span class="button-wrap">
        <div class="button button-raised button-primary button-pill">
          <%= link_to "Log In", login_path %>
        </div>
        <div class"shadow"></div>
      </span>
    </body>
  </html>

app/views/ideas/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
  </head>
  <header>
    <img class=""src="https://i.imgur.com/Q8V6tqc.jpg" alt="banner" height="300px" width="100%">
  </header>
  <body>
    <div class="btn btn-info">
      <%= button_to "Home", user_path(@user), method: "get" %><br/>
    </div>
    <div id="left"></div>
    <div id="right"></div>
    <div id="top"></div>
    <div id="bottom"></div>
    <div class="login">
      <div class="wrapper">
        <%= form_for [@user, @idea] do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "Idea Title*" %><br><br>
        <%= f.label :content %>
        <%= f.text_area :content, placeholder: "Idea*",:size => "38%x9%" %><br><br>
          <p> Category select  <%= f.collection_select(:categories_id, Category.all, :id, :title) %></p>
        <%= f.submit class: "sub-btn" %>

        <div class="flex-container">
          <div>
        <% Image.all.each do |image| %>
        <%= image_tag(image.url, :class=> "img-circular")%>
        <%= check_box_tag("image_url[]",image.id) %>
        <% end %>
        <% end %>
      </div>
    </div>
      </body>
 </html>

app/views/ideas/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <header>
    <img class=""src="https://i.imgur.com/zKoIAlP.jpg" alt="banner" height="300px" width="100%">
  </header>
  <body>
    <div class="btn btn-info">
      <%= button_to "Home", user_path(@user), method: "get" %><br/>
    </div>
    <div id="left"></div>
    <div id="right"></div>
    <div id="top"></div>
    <div id="bottom"></div>
    <div class="flex-container">
      <% @ideas.each do |idea| %>
      <div class="ideas">
      <h2><%= link_to idea.name, user_idea_path(@user, idea) %></h2>
      <br>
      <span class="button-wrap">
        <div class="button button-raised button-primary button-pill">
          <%= link_to "Delete",  user_idea_path(@user, idea), method: "delete" %>
        </div>
      </span>
      <span class="button-wrap">
        <div class="button button-raised button-primary button-pill">
          <%= link_to "Edit", edit_user_idea_path(@user, idea), method: "get" %>
        </div>
      </span>

      <br>
      <% end %>
    </div>

 </body>
</html>

app/views/ideas/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css">
  </head>
  <div class="anchored">
    <header>
      <img class=""src="https://i.imgur.com/PHJtGpv.jpg" alt="banner" height="300px" width="100%">
    </header>
  </div>
  <body>
    <div class="btn btn-info">
      <%= button_to "Home", user_path(@user), method: "get" %><br/>
    </div>
    <div id="left"></div>
    <div id="right"></div>
    <div id="top"></div>
    <div id="bottom"></div>
    <div class="login-3">
      <%= form_for [@user, @idea] do |f| %>
      <%= f.label :name  %>
      <%= f.text_field :name, placeholder: "Idea Title*" %>
      <%= f.label :content %>
      <%= f.text_area :content , placeholder: "Idea*",:size => "60%x12%"  %><br>
      <%= f.submit class: "sub-btn" %>
      <p> Category select  <%= f.collection_select(:categories_id, Category.all, :id, :title) %></p>
    </div>
    <% Image.all.each do |image| %>
    <%= image_tag(image.url, :class=> "img-circular")%>
    <%= check_box_tag("image_url[]",image.id) %>
    <% end %>
    <% end %>
 </body>
</html>

app/views/ideas/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
  </head>
  <header>
    <img class=""src="https://i.imgur.com/zKoIAlP.jpg" alt="banner" height="300px" width="100%">
  </header>
  <body>
    <div class="btn btn-info">
      <%= button_to "Home", user_path(@user), method: "get" %><br/>
    </div>
    <div class="btn btn-info">
      <%= button_to "Back to ideas", user_ideas_path(@user), method: "get" %><br/>
    </div>
    <div id="left"></div>
    <div id="right"></div>
    <div id="top"></div>
    <div id="bottom"></div>
    <div class="flex-container">
      <div>
      <h1>Title:</h1><h3><%= @idea.name %></h3>
      <h1>Body:</h1><%= @idea.content %><br>

      <p><% @idea.images.each do |image| %></p>
      <%= image_tag(image.url, size: "150x150" ) %><br/>
      <% end %>
      <span class="button-wrap">
        <div class="button button-raised button-primary button-pill">
          <%= link_to "Delete",  user_idea_path(@user, @idea), method: "delete" %>
        </div>
      </span>
      <span class="button-wrap">
        <div class="button button-raised button-primary button-pill">
          <%= link_to "Edit", edit_user_idea_path(@user, @idea), method: "get" %>
        </div>
      </span>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <div class="btn btn-info">
      <%= button_to "Home", user_path(@user), method: "get" %><br/>
    </div>
    <div id="left"></div>
<div id="right"></div>
<div id="top"></div>
<div id="bottom"></div>
<% @users.each do |user| %>
<ul><%= user.name %></ul>
<% end %>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <header>
  <img class=""src="https://i.imgur.com/ydRkyuu.jpg" alt="banner" height="300px" width="100%">
</header>
    <body>
      <div id="left"></div>
  <div id="right"></div>
  <div id="top"></div>
  <div id="bottom"></div>
      <div class="login-2">
        <h3>Sign up here!</h3>
          <div class="wrapper">
            <%= form_for @user do |f| %>
            <%= f.label :Username %>
            <%= f.text_field :name, placeholder: "new user name.*" %>
            <br>
            <%= f.label :Email %>
            <%= f.text_field :email, placeholder: "please enter your email.*" %>
            <br>
            <%= f.label :password %>
            <%= f.password_field :password, placeholder: "Choose a Password.*" %><br>
            <br>
            <p>* required field</p>
              <div class="btn btn-info">
              <%= f.submit "Create User", class: "sub-btn" %>
            </div>
              <% end %>
            </div>
          </div>
        </body>
    </html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css">
  </head>
  <body>
    <div id="left"></div>
    <div id="right"></div>
    <div id="top"></div>
    <div id="bottom"></div>
    <header>
      <img class="animated flipInY"src="https://i.imgur.com/tLVDqbW.jpg" alt="banner" height="300px" width="100%">
    </header>
    <div class="login">
      <h2> Welcome, <%= @user.name.capitalize %>!</h2><br/>
      <%= link_to "Add  Category", new_admin_category_path if current_user.admin? %>
       <br>
      <%= link_to "Add  Image", new_admin_image_path(current_user) if current_user.admin? %>
      <%= button_to "Add a New Idea", new_user_idea_path(@user), method: "get"%><br/>
      <%= button_to "View all ideas", user_ideas_path(@user), method: "get" %><br/>
      <span class="button-wrap">
        <div class="button button-raised button-primary button-pill">
          <%= link_to "Log Out", logout_path, method: :delete %>
        </div>
      </span>
    </div>
</html>